Fix 'variable referenced before assignment'
Since the cell value always contains the raw value,
add that first to avoid UnboundLocalError
in case a href is given in the column-definition tag.

This fixes the following error:
```
  File "/home/leostrakosch/Documents/SV/test-comp/benchexec/bin/../benchexec/tablegenerator/util.py", line 324, in <listcomp>
    clean_up_results(res, i) for i, res in enumerate(row["results"])
  File "/home/leostrakosch/Documents/SV/test-comp/benchexec/bin/../benchexec/tablegenerator/util.py", line 308, in clean_up_results
    for i, column in enumerate(res.columns)
  File "/home/leostrakosch/Documents/SV/test-comp/benchexec/bin/../benchexec/tablegenerator/util.py", line 308, in <listcomp>
    for i, column in enumerate(res.columns)
  File "/home/leostrakosch/Documents/SV/test-comp/benchexec/bin/../benchexec/tablegenerator/util.py", line 297, in prepare_values
    result["href"] = create_link(column.href, base_dir, run_result, href_base)
UnboundLocalError: local variable 'result' referenced before assignment
```