Add benchexec.result.RESULT_DONE
This is now the standard result for cases where true/false does not make
sense, and the result should also not be classified as error or unknown.

Other explanation:
ERROR: something went wrong
UNKNOWN: tool gives up, refuses to give an answer
TRUE: property holds
FALSE: property does not hold
DONE: no property given, or not a true/false property

The template tool-info module now returns DONE instead of UNKNOWN.
The tool-info module for javac now also returns DONE,
because TRUE does not really fit.

If DONE is returned, benchexec will automatically add information for
more specific termination reasons like timeout, segmentation fault,
etc., just like it already does for UNKNOWN and ERROR.
So for tools that do not need to output TRUE/FALSE
the default implementation of the template tool-info module
is now often enough.

This closes #385 by providing a more general alternative.